name: Knuu Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.21.1
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21.1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.5.3

      - name: Setup kubeconfig
        env:
          KUBECONFIG_FILE: ${{ secrets.KNUU_KUBECONFIG_FILE }}
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_FILE}" > $HOME/.kube/config

      - name: Run Tests
        run: go test -v ./...
        env:
          KNUU_NAMESPACE: "knuu-test"
          KNUU_SKIP_CLEANUP: "false"
